//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Submit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseReport
    {
        public int CaseReportID { get; set; }
        public int UserInformationID { get; set; }
        public System.DateTime DateReported { get; set; }
        public byte[] CaseReportPhoto { get; set; }
        public string CaseLocation { get; set; }
        public int EnvironmentalConcernID { get; set; }
        public int UpdatedStatusID { get; set; }
        public System.DateTime UpdatedStatusDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> VolunteerID { get; set; }
    }
}
